{
 "title": "Chia Monitor - Dual Node - Light",
 "description": "Displays all important metrics from your Chia farming node and all connected harvesters, collected by chia-monitor.",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "Pool",
    "query": {
     "query": "label_values(chia_current_pool_points, url)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Sync Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "chia_sync_status", "legendFormat": "{{job}}" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "chia_network_space{job=\"NODE1\"}",
     "legendFormat": "  Network Space"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 1, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "chia_diffculty{job=\"NODE1\"}",
     "legendFormat": "Difficulty"
    }
   ]
  },
  {
   "title": "Full Node Peers",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 2, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "chia_connections_count{type=\"Full Node\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Farmer Count",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 2, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "chia_connections_count{type=\"Farmer\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Harvester Count",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 2, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "chia_connections_count{type=\"Harvester\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "chia_price_usd_cent{job=\"NODE1\"}/100",
     "legendFormat": "XCH Price"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "chia_current_pool_points{url=\"$Pool\",job=\"NODE1\"}",
     "legendFormat": "Current Points"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "chia_current_pool_difficulty{url=\"$Pool\",job=\"NODE1\"}",
     "legendFormat": "Pool Difficulty"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 7, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(chia_plot_size)+sum(chia_portable_plot_size)",
     "legendFormat": "Total Plot Size"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "plots" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(chia_plot_count)+sum(chia_portable_plot_count)",
     "legendFormat": "Total Plot Count"
    }
   ]
  },
  {
   "title": "Points Success Rate Last 24H",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "chia_pool_points_acknowledged_24h{url=\"$Pool\"} / chia_pool_points_found_24h{url=\"$Pool\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Current Height:",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "chia_peak_height", "legendFormat": " " },
    {}
   ]
  },
  {
   "title": "Max Height:",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "chia_max_height", "legendFormat": " " }
   ]
  },
  {
   "title": "Total Plot Size By Node",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(chia_plot_size) by (job)+sum(chia_portable_plot_size) by (job)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Total Plot Count By Node",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "plots" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(chia_plot_count) by (job)+sum(chia_portable_plot_count) by (job)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Points Acknowledged Last 24H",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "chia_pool_points_acknowledged_24h{url=\"$Pool\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "XCH" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "chia_confirmed_total_mojos/1e12",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "chia_price_usd_cent/100 * chia_confirmed_total_mojos/1e12",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(chia_plot_size)", "legendFormat": "Total OG Size" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(chia_portable_plot_size)", "legendFormat": "Total NFT Size" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "plots" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(chia_plot_count)", "legendFormat": "Total OG Count" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "plots" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(chia_portable_plot_count)", "legendFormat": "Total NFT Count" }
   ]
  },
  {
   "title": "Points Found Last 24H",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "chia_pool_points_found_24h{url=\"$Pool\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "18.75 / ((sum(chia_plot_size) + sum(chia_portable_plot_size)) / sum(chia_network_space{job=\"NODE1\"}))",
     "legendFormat": "Expected Time To Win"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "XCH" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "chia_farmed_total_mojos{job=\"NODE1\"}/1e12",
     "legendFormat": "Total Farmed"
    }
   ]
  },
  {
   "title": "OG Size Delta",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    { "expr": "sum(chia_plot_size) by (job)", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "NFT Size Delta",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "expr": "sum(chia_portable_plot_size) by (job)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "OG Count Delta",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "plots" } },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    { "expr": "sum(chia_plot_count) by (job)", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "NFT Count Delta",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "plots" } },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "expr": "sum(chia_portable_plot_count) by (job)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Points Success Rate Since Start",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "chia_pool_points_acknowledged_since_start{url=\"$Pool\"} / chia_pool_points_found_since_start{url=\"$Pool\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "OG Plot Size",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 6, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(chia_plot_size) by (job)", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "NFT Plot Size",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 9, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(chia_portable_plot_size) by (job)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "OG Plot Count",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "plots" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(chia_plot_count) by (job)", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "NFT Plot Count",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 15, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "plots" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(chia_portable_plot_count) by (job)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Signage Points (per hour)",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(chia_signage_points_total[60m]) * 3600",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Points Acknowledged Since Start",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "chia_pool_points_acknowledged_since_start{url=\"$Pool\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Filters Passed (per hour)",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(chia_plots_passed_filter_total[60m]) * 3600",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Challenges (per hour)",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(chia_block_challenges_total[60m]) * 3600",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "OG Plot Size Per Harvester",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "chia_plot_size", "legendFormat": "{{ instance }} {{ host }}" }
   ]
  },
  {
   "title": "OG Plot Count Per Harvester",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "plots" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "chia_plot_count", "legendFormat": "{{ instance }} {{ host }}" }
   ]
  },
  {
   "title": "Points Found Since Start",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "chia_pool_points_found_since_start{url=\"$Pool\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Proofs Found (per hour)",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(chia_proofs_found_total[60m]) * 3600",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Proofs:",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "round(increase(chia_proofs_found_total[10y]))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "NFT Plot Size Per Harvester",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "chia_portable_plot_size", "legendFormat": "{{ instance }} {{ host }}" }
   ]
  },
  {
   "title": "NFT Plot Count Per Harvester",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "plots" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "chia_portable_plot_count", "legendFormat": "{{ instance }} {{ host }}" }
   ]
  }
 ]
}