"""Create composite primary key using ts and host for harvester_events table

Revision ID: 10bc373fc537
Revises: 7d540ed3aa62
Create Date: 2021-07-11 23:19:25.702482

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = '10bc373fc537'
down_revision = '7d540ed3aa62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        with op.batch_alter_table('harvester_events', schema=None) as batch_op:
            batch_op.drop_constraint('pk_harvester_events')
            batch_op.create_primary_key('pk_harvester_events', ['ts', 'host'])
    except ValueError:
        with op.batch_alter_table('harvester_events', schema=None) as batch_op:
            batch_op.create_primary_key('pk_harvester_events', ['ts', 'host'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        with op.batch_alter_table('harvester_events', schema=None) as batch_op:
            batch_op.drop_constraint('pk_harvester_events')
            batch_op.create_primary_key('pk_harvester_events', ['ts'])
    except ValueError:
        with op.batch_alter_table('harvester_events', schema=None) as batch_op:
            batch_op.create_primary_key('pk_harvester_events', ['ts'])
    # ### end Alembic commands ###
