"""Add p2_singleton_puzzle_hash and pool_url column to pool_state_events table

Revision ID: 2718ce248b8a
Revises: d360b24f64b2
Create Date: 2021-07-16 00:41:34.165166

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = '2718ce248b8a'
down_revision = 'd360b24f64b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pool_state_events', schema=None) as batch_op:
        batch_op.drop_constraint('pk_pool_state_events')
        batch_op.add_column(sa.Column('p2_singleton_puzzle_hash', sa.String(length=66), nullable=False, default=""))
        batch_op.add_column(sa.Column('pool_url', sa.String(length=255), nullable=True))
        batch_op.create_primary_key('pk_pool_state_events', ['ts', 'p2_singleton_puzzle_hash'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pool_state_events', schema=None) as batch_op:
        batch_op.drop_constraint('pk_pool_state_events')
        batch_op.drop_column('pool_url')
        batch_op.drop_column('p2_singleton_puzzle_hash')
        batch_op.create_primary_key('pk_pool_state_events', ['ts'])
    # ### end Alembic commands ###
