"""Add farmed column to wallet_balance_events table

Revision ID: 2d3d4960ffe8
Revises: ea982cfdfbf8
Create Date: 2021-07-13 19:10:25.727986

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = '2d3d4960ffe8'
down_revision = 'ea982cfdfbf8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wallet_balance_events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('farmed', sa.String(length=32), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wallet_balance_events', schema=None) as batch_op:
        batch_op.drop_column('farmed')

    # ### end Alembic commands ###
