"""Add portable_plot_count and portable_plot_size columns to harvester_events table

Revision ID: 30957ecc3bb4
Revises: 5ae65fde6009
Create Date: 2021-07-09 00:06:34.054897

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = '30957ecc3bb4'
down_revision = '5ae65fde6009'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('harvester_events', sa.Column('portable_plot_count', sa.Integer(), nullable=True))
    op.add_column('harvester_events', sa.Column('portable_plot_size', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('harvester_events', 'portable_plot_size')
    op.drop_column('harvester_events', 'portable_plot_count')
    # ### end Alembic commands ###
