"""Add points_found_24h and points_acknowledged_24h columns to pool_state_events table

Revision ID: 34c401ad62ee
Revises: 2718ce248b8a
Create Date: 2021-07-20 05:30:46.123024

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = '34c401ad62ee'
down_revision = '2718ce248b8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pool_state_events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('points_found_24h', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('points_acknowledged_24h', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pool_state_events', schema=None) as batch_op:
        batch_op.drop_column('points_acknowledged_24h')
        batch_op.drop_column('points_found_24h')

    # ### end Alembic commands ###
