"""Add harvester_count column to connection_events table

Revision ID: 5ae65fde6009
Revises: 9c7abcc3ed80
Create Date: 2021-06-13 23:00:22.008178

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = '5ae65fde6009'
down_revision = '9c7abcc3ed80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('connection_events', sa.Column('harvester_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('connection_events', 'harvester_count')
    # ### end Alembic commands ###
