"""Switch to autoincrement id as pk for signage_point_events

Revision ID: 704c57c068fb
Revises: 34c401ad62ee
Create Date: 2021-07-22 01:02:21.229183

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = '704c57c068fb'
down_revision = '34c401ad62ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        with op.batch_alter_table('signage_point_events', schema=None) as batch_op:
            batch_op.drop_constraint('pk_signage_point_events')
            batch_op.add_column(sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))
            batch_op.create_index(batch_op.f('ix_signage_point_events_ts'), ['ts'], unique=False)
            batch_op.create_primary_key('pk_signage_point_events', ['id'])
    except ValueError:
        with op.batch_alter_table('signage_point_events', schema=None) as batch_op:
            batch_op.add_column(sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))
            batch_op.create_index(batch_op.f('ix_signage_point_events_ts'), ['ts'], unique=False)
            batch_op.create_primary_key('pk_signage_point_events', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        with op.batch_alter_table('signage_point_events', schema=None) as batch_op:
            batch_op.drop_constraint('pk_signage_point_events')
            batch_op.drop_index(batch_op.f('ix_signage_point_events_ts'))
            batch_op.create_primary_key('pk_signage_point_events', ['ts'])
            batch_op.drop_column('id')
    except ValueError:
        with op.batch_alter_table('signage_point_events', schema=None) as batch_op:
            batch_op.drop_index(batch_op.f('ix_signage_point_events_ts'))
            batch_op.create_primary_key('pk_signage_point_events', ['ts'])
            batch_op.drop_column('id')
    # ### end Alembic commands ###
