"""Add host column to harvester_events table

Revision ID: 9c7abcc3ed80
Revises: d5e37981194d
Create Date: 2021-06-13 21:29:09.767452

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = '9c7abcc3ed80'
down_revision = 'd5e37981194d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('harvester_events', sa.Column('host', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('harvester_events', 'host')
    # ### end Alembic commands ###
