"""Add price_events table

Revision ID: d360b24f64b2
Revises: a5503c1613b5
Create Date: 2021-07-15 21:06:30.947766

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = 'd360b24f64b2'
down_revision = 'a5503c1613b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('price_events',
    sa.Column('ts', sa.DateTime(), nullable=False),
    sa.Column('usd_cents', sa.Integer(), nullable=True),
    sa.Column('eur_cents', sa.Integer(), nullable=True),
    sa.Column('btc_satoshi', sa.Integer(), nullable=True),
    sa.Column('eth_gwei', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('ts', name=op.f('pk_price_events'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('price_events')
    # ### end Alembic commands ###
