"""Add mempool_size column to blockchain_state_events table

Revision ID: da29916875ec
Revises: 664882eb4c78
Create Date: 2022-01-11 22:43:43.025752

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = 'da29916875ec'
down_revision = '664882eb4c78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blockchain_state_events', sa.Column('mempool_size', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blockchain_state_events', 'mempool_size')
    # ### end Alembic commands ###
